config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :projects, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  validates :project_id, presence: true
  validates :user_id, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :assignments
  has_many :users, through: :assignments
  has_many :tasks

  validates :name, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user, optional: true

  validates :name, presence: true
  validates :project_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :assignments
  has_many :projects, through: :assignments
  has_many :tasks

  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    first_name + " " + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @users = @project.users
    @tasks = @project.tasks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectPlanner</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<ul>
  <% @projects.each do |project| %>
    <li>
      <%= link_to project.name, project_path(project) %>
    </li>
  <% end %>
</ul>

app/views/projects/show.html.erb
<p>
  Name: <%= @project.name %>
</p>
<p>
  Description: <%= @project.description %>
</p>
<p>
  User List
</p>
<ul>
  <% @users.each do |user| %>
    <li>
      <p>
        <%= user.first_name %>
      </p>
      <p>
        <%= user.last_name %>
      </p>
      <p>
        <%= user.email %>
      </p>
    </li>
  <% end %>
</ul>
<p>
  Task List
</p>
<div class="tasks">
  <ul>
    <% @tasks.each do |task| %>
      <li>
        <p>
          <%= task.name %>
        </p>
        <% if task.due_date.present? %>
          <p> <%= task.due_date %> </p>
        <% end %>
        <% if task.description.present? %>
          <p> <%= task.description %> </p>
        <% end %>
        <p>
          User assigned to the task:
        </p>
        <% if task.user.present? %>
          <p>
            <%= task.user.full_name %>
          </p>
        <% end %>
        <% if task.user.present? && task.user.email.present? %>
          <p> <%= task.user.email %> </p>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>